version: '3'

services:
  speedtest:
    build: .
    environment:
      INTERVAL: 300
    volumes:
      - ./speedtest.json:/speedtest.json

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb-data:/var/lib/influxdb
