version: '3'

services:
  speedtest:
    build: .
    environment:
      INTERVAL: 300
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_USERNAME=myuser
      - INFLUXDB_PASSWORD=mypassword
      - INFLUXDB_DATABASE=mydb

    volumes:
      - ./speedtest.json:/speedtest.json

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=myuser
      - INFLUXDB_USER_PASSWORD=mypassword
    volumes:
      - ./influxdb-data:/var/lib/influxdb